# Generated by Django 5.2.8 on 2025-11-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclesapp', '0002_delete_vehiculo_alter_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='brand',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='model',
            new_name='modelo',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='numero_placa',
            field=models.CharField(default='SIN-PLACA', max_length=10, verbose_name='Número de placa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(choices=[('Rojo', 'Rojo'), ('Azul', 'Azul'), ('Verde', 'Verde'), ('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Gris', 'Gris'), ('Plateado', 'Plateado')], max_length=50, verbose_name='Color del vehículo'),
        ),
    ]
